"""auto-update new changes

Revision ID: 0690f6c4dc42
Revises: 4315830e586e
Create Date: 2023-08-12 09:22:48.988253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0690f6c4dc42'
down_revision = '4315830e586e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'phone_number', sa.Integer, nullable=False))
    op.create_unique_constraint('phone_number', 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_number', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
