"""added follows table

Revision ID: 3995a05f1a0e
Revises: 553263493146
Create Date: 2023-09-13 12:16:22.313555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3995a05f1a0e'
down_revision = '553263493146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
                    sa.Column('follower_id', sa.Integer(), nullable=False),
                    sa.Column('followed_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['followed_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['follower_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
