"""any changes

Revision ID: 39fbc195e222
Revises: b8171228ce86
Create Date: 2023-09-14 22:40:32.799815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fbc195e222'
down_revision = 'b8171228ce86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
