"""altered_phone_number_column

Revision ID: 553263493146
Revises: 0dd9a6c219ee
Create Date: 2023-09-12 22:47:06.317945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553263493146'
down_revision = '0dd9a6c219ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
                    existing_type=sa.String,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
                    existing_type=sa.String,
                    nullable=True)
    # ### end Alembic commands ###
