"""check changes

Revision ID: 5d310eaa3ac9
Revises: 0690f6c4dc42
Create Date: 2023-08-16 10:05:51.135509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d310eaa3ac9'
down_revision = '0690f6c4dc42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
