"""auto-update-phone-number-to-string

Revision ID: 8b1664379f1a
Revises: 5d310eaa3ac9
Create Date: 2023-08-16 13:49:33.705123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1664379f1a'
down_revision = '5d310eaa3ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
